"""empty message

Revision ID: 1840993d923f
Revises: None
Create Date: 2015-11-28 16:41:55.972024

"""

# revision identifiers, used by Alembic.
revision = '1840993d923f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('last_updated', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('bills', 'last_updated')
    ### end Alembic commands ###
